services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: react-flask-app-api
    ports:
      - "5000:5000"
  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: react-flask-app-client
    ports:
      - "80:80"